CATKIN_PACKAGE_PREFIX=""
PROJECT_ABSOLUTE_INCLUDE_DIRS="/home/mfiore/catkin_ws/src/appl/devel/include"
PROJECT_CATKIN_DEPENDS="roscpp;rospy;std_msgs;message_runtime"
PKG_CONFIG_LIBRARIES_WITH_PREFIX=""
PROJECT_NAME="appl"
PROJECT_SPACE_DIR="/home/mfiore/catkin_ws/src/appl/devel"
PROJECT_VERSION="0.0.0"
