/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/mfiore/catkin_ws/src/appl/srv/appl_request.srv
 *
 */


#ifndef APPL_MESSAGE_APPL_REQUESTRESPONSE_H
#define APPL_MESSAGE_APPL_REQUESTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace appl
{
template <class ContainerAllocator>
struct appl_requestResponse_
{
  typedef appl_requestResponse_<ContainerAllocator> Type;

  appl_requestResponse_()
    : action(0)
    , ystate()  {
    }
  appl_requestResponse_(const ContainerAllocator& _alloc)
    : action(0)
    , ystate(_alloc)  {
    }



   typedef int64_t _action_type;
  _action_type action;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _ystate_type;
  _ystate_type ystate;




  typedef boost::shared_ptr< ::appl::appl_requestResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::appl::appl_requestResponse_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct appl_requestResponse_

typedef ::appl::appl_requestResponse_<std::allocator<void> > appl_requestResponse;

typedef boost::shared_ptr< ::appl::appl_requestResponse > appl_requestResponsePtr;
typedef boost::shared_ptr< ::appl::appl_requestResponse const> appl_requestResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::appl::appl_requestResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::appl::appl_requestResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace appl

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/groovy/share/std_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::appl::appl_requestResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::appl::appl_requestResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::appl::appl_requestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::appl::appl_requestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::appl::appl_requestResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::appl::appl_requestResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::appl::appl_requestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "94be8c2fca635e52cb42f848cfa63f5f";
  }

  static const char* value(const ::appl::appl_requestResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x94be8c2fca635e52ULL;
  static const uint64_t static_value2 = 0xcb42f848cfa63f5fULL;
};

template<class ContainerAllocator>
struct DataType< ::appl::appl_requestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "appl/appl_requestResponse";
  }

  static const char* value(const ::appl::appl_requestResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::appl::appl_requestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 action\n\
string[] ystate\n\
\n\
\n\
";
  }

  static const char* value(const ::appl::appl_requestResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::appl::appl_requestResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action);
      stream.next(m.ystate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct appl_requestResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::appl::appl_requestResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::appl::appl_requestResponse_<ContainerAllocator>& v)
  {
    s << indent << "action: ";
    Printer<int64_t>::stream(s, indent + "  ", v.action);
    s << indent << "ystate[]" << std::endl;
    for (size_t i = 0; i < v.ystate.size(); ++i)
    {
      s << indent << "  ystate[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.ystate[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // APPL_MESSAGE_APPL_REQUESTRESPONSE_H
